package com.ly.back.framework.mybatis.mapper.sys;

import com.ly.back.framework.mybatis.model.sys.SysQueryJs;
import com.ly.back.framework.mybatis.model.sys.SysQueryJsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysQueryJsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    int countByExample(SysQueryJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    int deleteByExample(SysQueryJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    int insert(SysQueryJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    int insertSelective(SysQueryJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    List<SysQueryJs> selectByExampleWithRowbounds(SysQueryJsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    List<SysQueryJs> selectByExample(SysQueryJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    SysQueryJs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysQueryJs record, @Param("example") SysQueryJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysQueryJs record, @Param("example") SysQueryJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysQueryJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysQueryJs record);
}