package com.ly.back.framework.mybatis.mapper.sys;

import com.ly.back.framework.mybatis.model.sys.SysQueryFormType;
import com.ly.back.framework.mybatis.model.sys.SysQueryFormTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysQueryFormTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    int countByExample(SysQueryFormTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    int deleteByExample(SysQueryFormTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    int insert(SysQueryFormType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    int insertSelective(SysQueryFormType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    List<SysQueryFormType> selectByExampleWithRowbounds(SysQueryFormTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    List<SysQueryFormType> selectByExample(SysQueryFormTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    SysQueryFormType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysQueryFormType record, @Param("example") SysQueryFormTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysQueryFormType record, @Param("example") SysQueryFormTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysQueryFormType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysQueryFormType record);
}