package com.ly.back.framework.mybatis.mapper.sys;

import com.ly.back.framework.mybatis.model.sys.SysQueryField;
import com.ly.back.framework.mybatis.model.sys.SysQueryFieldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysQueryFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    int countByExample(SysQueryFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    int deleteByExample(SysQueryFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    int insert(SysQueryField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    int insertSelective(SysQueryField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    List<SysQueryField> selectByExampleWithRowbounds(SysQueryFieldExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    List<SysQueryField> selectByExample(SysQueryFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    SysQueryField selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysQueryField record, @Param("example") SysQueryFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysQueryField record, @Param("example") SysQueryFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysQueryField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysQueryField record);
}