package com.ly.back.framework.mybatis.mapper.sys;

import com.ly.back.framework.mybatis.model.sys.SysQuery;
import com.ly.back.framework.mybatis.model.sys.SysQueryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysQueryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int countByExample(SysQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int deleteByExample(SysQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int insert(SysQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int insertSelective(SysQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    List<SysQuery> selectByExampleWithBLOBsWithRowbounds(SysQueryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    List<SysQuery> selectByExampleWithBLOBs(SysQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    List<SysQuery> selectByExampleWithRowbounds(SysQueryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    List<SysQuery> selectByExample(SysQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    SysQuery selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysQuery record, @Param("example") SysQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SysQuery record, @Param("example") SysQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysQuery record, @Param("example") SysQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SysQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysQuery record);
}