package com.ly.gp.mybatis.model.info;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class GpDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public GpDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andMarketDateIsNull() {
            addCriterion("MARKET_DATE is null");
            return (Criteria) this;
        }

        public Criteria andMarketDateIsNotNull() {
            addCriterion("MARKET_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andMarketDateEqualTo(String value) {
            addCriterion("MARKET_DATE =", value, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateNotEqualTo(String value) {
            addCriterion("MARKET_DATE <>", value, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateGreaterThan(String value) {
            addCriterion("MARKET_DATE >", value, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateGreaterThanOrEqualTo(String value) {
            addCriterion("MARKET_DATE >=", value, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateLessThan(String value) {
            addCriterion("MARKET_DATE <", value, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateLessThanOrEqualTo(String value) {
            addCriterion("MARKET_DATE <=", value, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateLike(String value) {
            addCriterion("MARKET_DATE like", value, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateNotLike(String value) {
            addCriterion("MARKET_DATE not like", value, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateIn(List<String> values) {
            addCriterion("MARKET_DATE in", values, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateNotIn(List<String> values) {
            addCriterion("MARKET_DATE not in", values, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateBetween(String value1, String value2) {
            addCriterion("MARKET_DATE between", value1, value2, "marketDate");
            return (Criteria) this;
        }

        public Criteria andMarketDateNotBetween(String value1, String value2) {
            addCriterion("MARKET_DATE not between", value1, value2, "marketDate");
            return (Criteria) this;
        }

        public Criteria andOpenPriceIsNull() {
            addCriterion("OPEN_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andOpenPriceIsNotNull() {
            addCriterion("OPEN_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andOpenPriceEqualTo(BigDecimal value) {
            addCriterion("OPEN_PRICE =", value, "openPrice");
            return (Criteria) this;
        }

        public Criteria andOpenPriceNotEqualTo(BigDecimal value) {
            addCriterion("OPEN_PRICE <>", value, "openPrice");
            return (Criteria) this;
        }

        public Criteria andOpenPriceGreaterThan(BigDecimal value) {
            addCriterion("OPEN_PRICE >", value, "openPrice");
            return (Criteria) this;
        }

        public Criteria andOpenPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OPEN_PRICE >=", value, "openPrice");
            return (Criteria) this;
        }

        public Criteria andOpenPriceLessThan(BigDecimal value) {
            addCriterion("OPEN_PRICE <", value, "openPrice");
            return (Criteria) this;
        }

        public Criteria andOpenPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OPEN_PRICE <=", value, "openPrice");
            return (Criteria) this;
        }

        public Criteria andOpenPriceIn(List<BigDecimal> values) {
            addCriterion("OPEN_PRICE in", values, "openPrice");
            return (Criteria) this;
        }

        public Criteria andOpenPriceNotIn(List<BigDecimal> values) {
            addCriterion("OPEN_PRICE not in", values, "openPrice");
            return (Criteria) this;
        }

        public Criteria andOpenPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OPEN_PRICE between", value1, value2, "openPrice");
            return (Criteria) this;
        }

        public Criteria andOpenPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OPEN_PRICE not between", value1, value2, "openPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceIsNull() {
            addCriterion("LOW_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andLowPriceIsNotNull() {
            addCriterion("LOW_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andLowPriceEqualTo(BigDecimal value) {
            addCriterion("LOW_PRICE =", value, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceNotEqualTo(BigDecimal value) {
            addCriterion("LOW_PRICE <>", value, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceGreaterThan(BigDecimal value) {
            addCriterion("LOW_PRICE >", value, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOW_PRICE >=", value, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceLessThan(BigDecimal value) {
            addCriterion("LOW_PRICE <", value, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOW_PRICE <=", value, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceIn(List<BigDecimal> values) {
            addCriterion("LOW_PRICE in", values, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceNotIn(List<BigDecimal> values) {
            addCriterion("LOW_PRICE not in", values, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOW_PRICE between", value1, value2, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andLowPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOW_PRICE not between", value1, value2, "lowPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceIsNull() {
            addCriterion("HIGHT_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andHightPriceIsNotNull() {
            addCriterion("HIGHT_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andHightPriceEqualTo(BigDecimal value) {
            addCriterion("HIGHT_PRICE =", value, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceNotEqualTo(BigDecimal value) {
            addCriterion("HIGHT_PRICE <>", value, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceGreaterThan(BigDecimal value) {
            addCriterion("HIGHT_PRICE >", value, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HIGHT_PRICE >=", value, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceLessThan(BigDecimal value) {
            addCriterion("HIGHT_PRICE <", value, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HIGHT_PRICE <=", value, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceIn(List<BigDecimal> values) {
            addCriterion("HIGHT_PRICE in", values, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceNotIn(List<BigDecimal> values) {
            addCriterion("HIGHT_PRICE not in", values, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HIGHT_PRICE between", value1, value2, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andHightPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HIGHT_PRICE not between", value1, value2, "hightPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceIsNull() {
            addCriterion("FINAL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andFinalPriceIsNotNull() {
            addCriterion("FINAL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andFinalPriceEqualTo(BigDecimal value) {
            addCriterion("FINAL_PRICE =", value, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceNotEqualTo(BigDecimal value) {
            addCriterion("FINAL_PRICE <>", value, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceGreaterThan(BigDecimal value) {
            addCriterion("FINAL_PRICE >", value, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FINAL_PRICE >=", value, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceLessThan(BigDecimal value) {
            addCriterion("FINAL_PRICE <", value, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FINAL_PRICE <=", value, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceIn(List<BigDecimal> values) {
            addCriterion("FINAL_PRICE in", values, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceNotIn(List<BigDecimal> values) {
            addCriterion("FINAL_PRICE not in", values, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FINAL_PRICE between", value1, value2, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andFinalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FINAL_PRICE not between", value1, value2, "finalPrice");
            return (Criteria) this;
        }

        public Criteria andTradCountIsNull() {
            addCriterion("TRAD_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andTradCountIsNotNull() {
            addCriterion("TRAD_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTradCountEqualTo(BigDecimal value) {
            addCriterion("TRAD_COUNT =", value, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradCountNotEqualTo(BigDecimal value) {
            addCriterion("TRAD_COUNT <>", value, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradCountGreaterThan(BigDecimal value) {
            addCriterion("TRAD_COUNT >", value, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradCountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAD_COUNT >=", value, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradCountLessThan(BigDecimal value) {
            addCriterion("TRAD_COUNT <", value, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradCountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAD_COUNT <=", value, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradCountIn(List<BigDecimal> values) {
            addCriterion("TRAD_COUNT in", values, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradCountNotIn(List<BigDecimal> values) {
            addCriterion("TRAD_COUNT not in", values, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradCountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAD_COUNT between", value1, value2, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradCountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAD_COUNT not between", value1, value2, "tradCount");
            return (Criteria) this;
        }

        public Criteria andTradPriceIsNull() {
            addCriterion("TRAD_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andTradPriceIsNotNull() {
            addCriterion("TRAD_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andTradPriceEqualTo(BigDecimal value) {
            addCriterion("TRAD_PRICE =", value, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andTradPriceNotEqualTo(BigDecimal value) {
            addCriterion("TRAD_PRICE <>", value, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andTradPriceGreaterThan(BigDecimal value) {
            addCriterion("TRAD_PRICE >", value, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andTradPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAD_PRICE >=", value, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andTradPriceLessThan(BigDecimal value) {
            addCriterion("TRAD_PRICE <", value, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andTradPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAD_PRICE <=", value, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andTradPriceIn(List<BigDecimal> values) {
            addCriterion("TRAD_PRICE in", values, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andTradPriceNotIn(List<BigDecimal> values) {
            addCriterion("TRAD_PRICE not in", values, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andTradPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAD_PRICE between", value1, value2, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andTradPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAD_PRICE not between", value1, value2, "tradPrice");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCollectNumIsNull() {
            addCriterion("COLLECT_NUM is null");
            return (Criteria) this;
        }

        public Criteria andCollectNumIsNotNull() {
            addCriterion("COLLECT_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andCollectNumEqualTo(Long value) {
            addCriterion("COLLECT_NUM =", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumNotEqualTo(Long value) {
            addCriterion("COLLECT_NUM <>", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumGreaterThan(Long value) {
            addCriterion("COLLECT_NUM >", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumGreaterThanOrEqualTo(Long value) {
            addCriterion("COLLECT_NUM >=", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumLessThan(Long value) {
            addCriterion("COLLECT_NUM <", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumLessThanOrEqualTo(Long value) {
            addCriterion("COLLECT_NUM <=", value, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumIn(List<Long> values) {
            addCriterion("COLLECT_NUM in", values, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumNotIn(List<Long> values) {
            addCriterion("COLLECT_NUM not in", values, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumBetween(Long value1, Long value2) {
            addCriterion("COLLECT_NUM between", value1, value2, "collectNum");
            return (Criteria) this;
        }

        public Criteria andCollectNumNotBetween(Long value1, Long value2) {
            addCriterion("COLLECT_NUM not between", value1, value2, "collectNum");
            return (Criteria) this;
        }

        public Criteria andIncreaseIsNull() {
            addCriterion("INCREASE is null");
            return (Criteria) this;
        }

        public Criteria andIncreaseIsNotNull() {
            addCriterion("INCREASE is not null");
            return (Criteria) this;
        }

        public Criteria andIncreaseEqualTo(BigDecimal value) {
            addCriterion("INCREASE =", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseNotEqualTo(BigDecimal value) {
            addCriterion("INCREASE <>", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseGreaterThan(BigDecimal value) {
            addCriterion("INCREASE >", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INCREASE >=", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseLessThan(BigDecimal value) {
            addCriterion("INCREASE <", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INCREASE <=", value, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseIn(List<BigDecimal> values) {
            addCriterion("INCREASE in", values, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseNotIn(List<BigDecimal> values) {
            addCriterion("INCREASE not in", values, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INCREASE between", value1, value2, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INCREASE not between", value1, value2, "increase");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyIsNull() {
            addCriterion("INCREASE_MONEY is null");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyIsNotNull() {
            addCriterion("INCREASE_MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyEqualTo(BigDecimal value) {
            addCriterion("INCREASE_MONEY =", value, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyNotEqualTo(BigDecimal value) {
            addCriterion("INCREASE_MONEY <>", value, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyGreaterThan(BigDecimal value) {
            addCriterion("INCREASE_MONEY >", value, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INCREASE_MONEY >=", value, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyLessThan(BigDecimal value) {
            addCriterion("INCREASE_MONEY <", value, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INCREASE_MONEY <=", value, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyIn(List<BigDecimal> values) {
            addCriterion("INCREASE_MONEY in", values, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyNotIn(List<BigDecimal> values) {
            addCriterion("INCREASE_MONEY not in", values, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INCREASE_MONEY between", value1, value2, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andIncreaseMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INCREASE_MONEY not between", value1, value2, "increaseMoney");
            return (Criteria) this;
        }

        public Criteria andVar3IsNull() {
            addCriterion("VAR_3 is null");
            return (Criteria) this;
        }

        public Criteria andVar3IsNotNull() {
            addCriterion("VAR_3 is not null");
            return (Criteria) this;
        }

        public Criteria andVar3EqualTo(BigDecimal value) {
            addCriterion("VAR_3 =", value, "var3");
            return (Criteria) this;
        }

        public Criteria andVar3NotEqualTo(BigDecimal value) {
            addCriterion("VAR_3 <>", value, "var3");
            return (Criteria) this;
        }

        public Criteria andVar3GreaterThan(BigDecimal value) {
            addCriterion("VAR_3 >", value, "var3");
            return (Criteria) this;
        }

        public Criteria andVar3GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_3 >=", value, "var3");
            return (Criteria) this;
        }

        public Criteria andVar3LessThan(BigDecimal value) {
            addCriterion("VAR_3 <", value, "var3");
            return (Criteria) this;
        }

        public Criteria andVar3LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_3 <=", value, "var3");
            return (Criteria) this;
        }

        public Criteria andVar3In(List<BigDecimal> values) {
            addCriterion("VAR_3 in", values, "var3");
            return (Criteria) this;
        }

        public Criteria andVar3NotIn(List<BigDecimal> values) {
            addCriterion("VAR_3 not in", values, "var3");
            return (Criteria) this;
        }

        public Criteria andVar3Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_3 between", value1, value2, "var3");
            return (Criteria) this;
        }

        public Criteria andVar3NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_3 not between", value1, value2, "var3");
            return (Criteria) this;
        }

        public Criteria andVar5IsNull() {
            addCriterion("VAR_5 is null");
            return (Criteria) this;
        }

        public Criteria andVar5IsNotNull() {
            addCriterion("VAR_5 is not null");
            return (Criteria) this;
        }

        public Criteria andVar5EqualTo(BigDecimal value) {
            addCriterion("VAR_5 =", value, "var5");
            return (Criteria) this;
        }

        public Criteria andVar5NotEqualTo(BigDecimal value) {
            addCriterion("VAR_5 <>", value, "var5");
            return (Criteria) this;
        }

        public Criteria andVar5GreaterThan(BigDecimal value) {
            addCriterion("VAR_5 >", value, "var5");
            return (Criteria) this;
        }

        public Criteria andVar5GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_5 >=", value, "var5");
            return (Criteria) this;
        }

        public Criteria andVar5LessThan(BigDecimal value) {
            addCriterion("VAR_5 <", value, "var5");
            return (Criteria) this;
        }

        public Criteria andVar5LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_5 <=", value, "var5");
            return (Criteria) this;
        }

        public Criteria andVar5In(List<BigDecimal> values) {
            addCriterion("VAR_5 in", values, "var5");
            return (Criteria) this;
        }

        public Criteria andVar5NotIn(List<BigDecimal> values) {
            addCriterion("VAR_5 not in", values, "var5");
            return (Criteria) this;
        }

        public Criteria andVar5Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_5 between", value1, value2, "var5");
            return (Criteria) this;
        }

        public Criteria andVar5NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_5 not between", value1, value2, "var5");
            return (Criteria) this;
        }

        public Criteria andVar8IsNull() {
            addCriterion("VAR_8 is null");
            return (Criteria) this;
        }

        public Criteria andVar8IsNotNull() {
            addCriterion("VAR_8 is not null");
            return (Criteria) this;
        }

        public Criteria andVar8EqualTo(BigDecimal value) {
            addCriterion("VAR_8 =", value, "var8");
            return (Criteria) this;
        }

        public Criteria andVar8NotEqualTo(BigDecimal value) {
            addCriterion("VAR_8 <>", value, "var8");
            return (Criteria) this;
        }

        public Criteria andVar8GreaterThan(BigDecimal value) {
            addCriterion("VAR_8 >", value, "var8");
            return (Criteria) this;
        }

        public Criteria andVar8GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_8 >=", value, "var8");
            return (Criteria) this;
        }

        public Criteria andVar8LessThan(BigDecimal value) {
            addCriterion("VAR_8 <", value, "var8");
            return (Criteria) this;
        }

        public Criteria andVar8LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_8 <=", value, "var8");
            return (Criteria) this;
        }

        public Criteria andVar8In(List<BigDecimal> values) {
            addCriterion("VAR_8 in", values, "var8");
            return (Criteria) this;
        }

        public Criteria andVar8NotIn(List<BigDecimal> values) {
            addCriterion("VAR_8 not in", values, "var8");
            return (Criteria) this;
        }

        public Criteria andVar8Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_8 between", value1, value2, "var8");
            return (Criteria) this;
        }

        public Criteria andVar8NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_8 not between", value1, value2, "var8");
            return (Criteria) this;
        }

        public Criteria andVar10IsNull() {
            addCriterion("VAR_10 is null");
            return (Criteria) this;
        }

        public Criteria andVar10IsNotNull() {
            addCriterion("VAR_10 is not null");
            return (Criteria) this;
        }

        public Criteria andVar10EqualTo(BigDecimal value) {
            addCriterion("VAR_10 =", value, "var10");
            return (Criteria) this;
        }

        public Criteria andVar10NotEqualTo(BigDecimal value) {
            addCriterion("VAR_10 <>", value, "var10");
            return (Criteria) this;
        }

        public Criteria andVar10GreaterThan(BigDecimal value) {
            addCriterion("VAR_10 >", value, "var10");
            return (Criteria) this;
        }

        public Criteria andVar10GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_10 >=", value, "var10");
            return (Criteria) this;
        }

        public Criteria andVar10LessThan(BigDecimal value) {
            addCriterion("VAR_10 <", value, "var10");
            return (Criteria) this;
        }

        public Criteria andVar10LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_10 <=", value, "var10");
            return (Criteria) this;
        }

        public Criteria andVar10In(List<BigDecimal> values) {
            addCriterion("VAR_10 in", values, "var10");
            return (Criteria) this;
        }

        public Criteria andVar10NotIn(List<BigDecimal> values) {
            addCriterion("VAR_10 not in", values, "var10");
            return (Criteria) this;
        }

        public Criteria andVar10Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_10 between", value1, value2, "var10");
            return (Criteria) this;
        }

        public Criteria andVar10NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_10 not between", value1, value2, "var10");
            return (Criteria) this;
        }

        public Criteria andVar12IsNull() {
            addCriterion("VAR_12 is null");
            return (Criteria) this;
        }

        public Criteria andVar12IsNotNull() {
            addCriterion("VAR_12 is not null");
            return (Criteria) this;
        }

        public Criteria andVar12EqualTo(BigDecimal value) {
            addCriterion("VAR_12 =", value, "var12");
            return (Criteria) this;
        }

        public Criteria andVar12NotEqualTo(BigDecimal value) {
            addCriterion("VAR_12 <>", value, "var12");
            return (Criteria) this;
        }

        public Criteria andVar12GreaterThan(BigDecimal value) {
            addCriterion("VAR_12 >", value, "var12");
            return (Criteria) this;
        }

        public Criteria andVar12GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_12 >=", value, "var12");
            return (Criteria) this;
        }

        public Criteria andVar12LessThan(BigDecimal value) {
            addCriterion("VAR_12 <", value, "var12");
            return (Criteria) this;
        }

        public Criteria andVar12LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_12 <=", value, "var12");
            return (Criteria) this;
        }

        public Criteria andVar12In(List<BigDecimal> values) {
            addCriterion("VAR_12 in", values, "var12");
            return (Criteria) this;
        }

        public Criteria andVar12NotIn(List<BigDecimal> values) {
            addCriterion("VAR_12 not in", values, "var12");
            return (Criteria) this;
        }

        public Criteria andVar12Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_12 between", value1, value2, "var12");
            return (Criteria) this;
        }

        public Criteria andVar12NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_12 not between", value1, value2, "var12");
            return (Criteria) this;
        }

        public Criteria andVar15IsNull() {
            addCriterion("VAR_15 is null");
            return (Criteria) this;
        }

        public Criteria andVar15IsNotNull() {
            addCriterion("VAR_15 is not null");
            return (Criteria) this;
        }

        public Criteria andVar15EqualTo(BigDecimal value) {
            addCriterion("VAR_15 =", value, "var15");
            return (Criteria) this;
        }

        public Criteria andVar15NotEqualTo(BigDecimal value) {
            addCriterion("VAR_15 <>", value, "var15");
            return (Criteria) this;
        }

        public Criteria andVar15GreaterThan(BigDecimal value) {
            addCriterion("VAR_15 >", value, "var15");
            return (Criteria) this;
        }

        public Criteria andVar15GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_15 >=", value, "var15");
            return (Criteria) this;
        }

        public Criteria andVar15LessThan(BigDecimal value) {
            addCriterion("VAR_15 <", value, "var15");
            return (Criteria) this;
        }

        public Criteria andVar15LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_15 <=", value, "var15");
            return (Criteria) this;
        }

        public Criteria andVar15In(List<BigDecimal> values) {
            addCriterion("VAR_15 in", values, "var15");
            return (Criteria) this;
        }

        public Criteria andVar15NotIn(List<BigDecimal> values) {
            addCriterion("VAR_15 not in", values, "var15");
            return (Criteria) this;
        }

        public Criteria andVar15Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_15 between", value1, value2, "var15");
            return (Criteria) this;
        }

        public Criteria andVar15NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_15 not between", value1, value2, "var15");
            return (Criteria) this;
        }

        public Criteria andVar18IsNull() {
            addCriterion("VAR_18 is null");
            return (Criteria) this;
        }

        public Criteria andVar18IsNotNull() {
            addCriterion("VAR_18 is not null");
            return (Criteria) this;
        }

        public Criteria andVar18EqualTo(BigDecimal value) {
            addCriterion("VAR_18 =", value, "var18");
            return (Criteria) this;
        }

        public Criteria andVar18NotEqualTo(BigDecimal value) {
            addCriterion("VAR_18 <>", value, "var18");
            return (Criteria) this;
        }

        public Criteria andVar18GreaterThan(BigDecimal value) {
            addCriterion("VAR_18 >", value, "var18");
            return (Criteria) this;
        }

        public Criteria andVar18GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_18 >=", value, "var18");
            return (Criteria) this;
        }

        public Criteria andVar18LessThan(BigDecimal value) {
            addCriterion("VAR_18 <", value, "var18");
            return (Criteria) this;
        }

        public Criteria andVar18LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_18 <=", value, "var18");
            return (Criteria) this;
        }

        public Criteria andVar18In(List<BigDecimal> values) {
            addCriterion("VAR_18 in", values, "var18");
            return (Criteria) this;
        }

        public Criteria andVar18NotIn(List<BigDecimal> values) {
            addCriterion("VAR_18 not in", values, "var18");
            return (Criteria) this;
        }

        public Criteria andVar18Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_18 between", value1, value2, "var18");
            return (Criteria) this;
        }

        public Criteria andVar18NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_18 not between", value1, value2, "var18");
            return (Criteria) this;
        }

        public Criteria andVar20IsNull() {
            addCriterion("VAR_20 is null");
            return (Criteria) this;
        }

        public Criteria andVar20IsNotNull() {
            addCriterion("VAR_20 is not null");
            return (Criteria) this;
        }

        public Criteria andVar20EqualTo(BigDecimal value) {
            addCriterion("VAR_20 =", value, "var20");
            return (Criteria) this;
        }

        public Criteria andVar20NotEqualTo(BigDecimal value) {
            addCriterion("VAR_20 <>", value, "var20");
            return (Criteria) this;
        }

        public Criteria andVar20GreaterThan(BigDecimal value) {
            addCriterion("VAR_20 >", value, "var20");
            return (Criteria) this;
        }

        public Criteria andVar20GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_20 >=", value, "var20");
            return (Criteria) this;
        }

        public Criteria andVar20LessThan(BigDecimal value) {
            addCriterion("VAR_20 <", value, "var20");
            return (Criteria) this;
        }

        public Criteria andVar20LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_20 <=", value, "var20");
            return (Criteria) this;
        }

        public Criteria andVar20In(List<BigDecimal> values) {
            addCriterion("VAR_20 in", values, "var20");
            return (Criteria) this;
        }

        public Criteria andVar20NotIn(List<BigDecimal> values) {
            addCriterion("VAR_20 not in", values, "var20");
            return (Criteria) this;
        }

        public Criteria andVar20Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_20 between", value1, value2, "var20");
            return (Criteria) this;
        }

        public Criteria andVar20NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_20 not between", value1, value2, "var20");
            return (Criteria) this;
        }

        public Criteria andVar25IsNull() {
            addCriterion("VAR_25 is null");
            return (Criteria) this;
        }

        public Criteria andVar25IsNotNull() {
            addCriterion("VAR_25 is not null");
            return (Criteria) this;
        }

        public Criteria andVar25EqualTo(BigDecimal value) {
            addCriterion("VAR_25 =", value, "var25");
            return (Criteria) this;
        }

        public Criteria andVar25NotEqualTo(BigDecimal value) {
            addCriterion("VAR_25 <>", value, "var25");
            return (Criteria) this;
        }

        public Criteria andVar25GreaterThan(BigDecimal value) {
            addCriterion("VAR_25 >", value, "var25");
            return (Criteria) this;
        }

        public Criteria andVar25GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_25 >=", value, "var25");
            return (Criteria) this;
        }

        public Criteria andVar25LessThan(BigDecimal value) {
            addCriterion("VAR_25 <", value, "var25");
            return (Criteria) this;
        }

        public Criteria andVar25LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_25 <=", value, "var25");
            return (Criteria) this;
        }

        public Criteria andVar25In(List<BigDecimal> values) {
            addCriterion("VAR_25 in", values, "var25");
            return (Criteria) this;
        }

        public Criteria andVar25NotIn(List<BigDecimal> values) {
            addCriterion("VAR_25 not in", values, "var25");
            return (Criteria) this;
        }

        public Criteria andVar25Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_25 between", value1, value2, "var25");
            return (Criteria) this;
        }

        public Criteria andVar25NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_25 not between", value1, value2, "var25");
            return (Criteria) this;
        }

        public Criteria andVar30IsNull() {
            addCriterion("VAR_30 is null");
            return (Criteria) this;
        }

        public Criteria andVar30IsNotNull() {
            addCriterion("VAR_30 is not null");
            return (Criteria) this;
        }

        public Criteria andVar30EqualTo(BigDecimal value) {
            addCriterion("VAR_30 =", value, "var30");
            return (Criteria) this;
        }

        public Criteria andVar30NotEqualTo(BigDecimal value) {
            addCriterion("VAR_30 <>", value, "var30");
            return (Criteria) this;
        }

        public Criteria andVar30GreaterThan(BigDecimal value) {
            addCriterion("VAR_30 >", value, "var30");
            return (Criteria) this;
        }

        public Criteria andVar30GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_30 >=", value, "var30");
            return (Criteria) this;
        }

        public Criteria andVar30LessThan(BigDecimal value) {
            addCriterion("VAR_30 <", value, "var30");
            return (Criteria) this;
        }

        public Criteria andVar30LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_30 <=", value, "var30");
            return (Criteria) this;
        }

        public Criteria andVar30In(List<BigDecimal> values) {
            addCriterion("VAR_30 in", values, "var30");
            return (Criteria) this;
        }

        public Criteria andVar30NotIn(List<BigDecimal> values) {
            addCriterion("VAR_30 not in", values, "var30");
            return (Criteria) this;
        }

        public Criteria andVar30Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_30 between", value1, value2, "var30");
            return (Criteria) this;
        }

        public Criteria andVar30NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_30 not between", value1, value2, "var30");
            return (Criteria) this;
        }

        public Criteria andVar35IsNull() {
            addCriterion("VAR_35 is null");
            return (Criteria) this;
        }

        public Criteria andVar35IsNotNull() {
            addCriterion("VAR_35 is not null");
            return (Criteria) this;
        }

        public Criteria andVar35EqualTo(BigDecimal value) {
            addCriterion("VAR_35 =", value, "var35");
            return (Criteria) this;
        }

        public Criteria andVar35NotEqualTo(BigDecimal value) {
            addCriterion("VAR_35 <>", value, "var35");
            return (Criteria) this;
        }

        public Criteria andVar35GreaterThan(BigDecimal value) {
            addCriterion("VAR_35 >", value, "var35");
            return (Criteria) this;
        }

        public Criteria andVar35GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_35 >=", value, "var35");
            return (Criteria) this;
        }

        public Criteria andVar35LessThan(BigDecimal value) {
            addCriterion("VAR_35 <", value, "var35");
            return (Criteria) this;
        }

        public Criteria andVar35LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_35 <=", value, "var35");
            return (Criteria) this;
        }

        public Criteria andVar35In(List<BigDecimal> values) {
            addCriterion("VAR_35 in", values, "var35");
            return (Criteria) this;
        }

        public Criteria andVar35NotIn(List<BigDecimal> values) {
            addCriterion("VAR_35 not in", values, "var35");
            return (Criteria) this;
        }

        public Criteria andVar35Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_35 between", value1, value2, "var35");
            return (Criteria) this;
        }

        public Criteria andVar35NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_35 not between", value1, value2, "var35");
            return (Criteria) this;
        }

        public Criteria andVar40IsNull() {
            addCriterion("VAR_40 is null");
            return (Criteria) this;
        }

        public Criteria andVar40IsNotNull() {
            addCriterion("VAR_40 is not null");
            return (Criteria) this;
        }

        public Criteria andVar40EqualTo(BigDecimal value) {
            addCriterion("VAR_40 =", value, "var40");
            return (Criteria) this;
        }

        public Criteria andVar40NotEqualTo(BigDecimal value) {
            addCriterion("VAR_40 <>", value, "var40");
            return (Criteria) this;
        }

        public Criteria andVar40GreaterThan(BigDecimal value) {
            addCriterion("VAR_40 >", value, "var40");
            return (Criteria) this;
        }

        public Criteria andVar40GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_40 >=", value, "var40");
            return (Criteria) this;
        }

        public Criteria andVar40LessThan(BigDecimal value) {
            addCriterion("VAR_40 <", value, "var40");
            return (Criteria) this;
        }

        public Criteria andVar40LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_40 <=", value, "var40");
            return (Criteria) this;
        }

        public Criteria andVar40In(List<BigDecimal> values) {
            addCriterion("VAR_40 in", values, "var40");
            return (Criteria) this;
        }

        public Criteria andVar40NotIn(List<BigDecimal> values) {
            addCriterion("VAR_40 not in", values, "var40");
            return (Criteria) this;
        }

        public Criteria andVar40Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_40 between", value1, value2, "var40");
            return (Criteria) this;
        }

        public Criteria andVar40NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_40 not between", value1, value2, "var40");
            return (Criteria) this;
        }

        public Criteria andVar45IsNull() {
            addCriterion("VAR_45 is null");
            return (Criteria) this;
        }

        public Criteria andVar45IsNotNull() {
            addCriterion("VAR_45 is not null");
            return (Criteria) this;
        }

        public Criteria andVar45EqualTo(BigDecimal value) {
            addCriterion("VAR_45 =", value, "var45");
            return (Criteria) this;
        }

        public Criteria andVar45NotEqualTo(BigDecimal value) {
            addCriterion("VAR_45 <>", value, "var45");
            return (Criteria) this;
        }

        public Criteria andVar45GreaterThan(BigDecimal value) {
            addCriterion("VAR_45 >", value, "var45");
            return (Criteria) this;
        }

        public Criteria andVar45GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_45 >=", value, "var45");
            return (Criteria) this;
        }

        public Criteria andVar45LessThan(BigDecimal value) {
            addCriterion("VAR_45 <", value, "var45");
            return (Criteria) this;
        }

        public Criteria andVar45LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_45 <=", value, "var45");
            return (Criteria) this;
        }

        public Criteria andVar45In(List<BigDecimal> values) {
            addCriterion("VAR_45 in", values, "var45");
            return (Criteria) this;
        }

        public Criteria andVar45NotIn(List<BigDecimal> values) {
            addCriterion("VAR_45 not in", values, "var45");
            return (Criteria) this;
        }

        public Criteria andVar45Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_45 between", value1, value2, "var45");
            return (Criteria) this;
        }

        public Criteria andVar45NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_45 not between", value1, value2, "var45");
            return (Criteria) this;
        }

        public Criteria andVar50IsNull() {
            addCriterion("VAR_50 is null");
            return (Criteria) this;
        }

        public Criteria andVar50IsNotNull() {
            addCriterion("VAR_50 is not null");
            return (Criteria) this;
        }

        public Criteria andVar50EqualTo(BigDecimal value) {
            addCriterion("VAR_50 =", value, "var50");
            return (Criteria) this;
        }

        public Criteria andVar50NotEqualTo(BigDecimal value) {
            addCriterion("VAR_50 <>", value, "var50");
            return (Criteria) this;
        }

        public Criteria andVar50GreaterThan(BigDecimal value) {
            addCriterion("VAR_50 >", value, "var50");
            return (Criteria) this;
        }

        public Criteria andVar50GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_50 >=", value, "var50");
            return (Criteria) this;
        }

        public Criteria andVar50LessThan(BigDecimal value) {
            addCriterion("VAR_50 <", value, "var50");
            return (Criteria) this;
        }

        public Criteria andVar50LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_50 <=", value, "var50");
            return (Criteria) this;
        }

        public Criteria andVar50In(List<BigDecimal> values) {
            addCriterion("VAR_50 in", values, "var50");
            return (Criteria) this;
        }

        public Criteria andVar50NotIn(List<BigDecimal> values) {
            addCriterion("VAR_50 not in", values, "var50");
            return (Criteria) this;
        }

        public Criteria andVar50Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_50 between", value1, value2, "var50");
            return (Criteria) this;
        }

        public Criteria andVar50NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_50 not between", value1, value2, "var50");
            return (Criteria) this;
        }

        public Criteria andVar55IsNull() {
            addCriterion("VAR_55 is null");
            return (Criteria) this;
        }

        public Criteria andVar55IsNotNull() {
            addCriterion("VAR_55 is not null");
            return (Criteria) this;
        }

        public Criteria andVar55EqualTo(BigDecimal value) {
            addCriterion("VAR_55 =", value, "var55");
            return (Criteria) this;
        }

        public Criteria andVar55NotEqualTo(BigDecimal value) {
            addCriterion("VAR_55 <>", value, "var55");
            return (Criteria) this;
        }

        public Criteria andVar55GreaterThan(BigDecimal value) {
            addCriterion("VAR_55 >", value, "var55");
            return (Criteria) this;
        }

        public Criteria andVar55GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_55 >=", value, "var55");
            return (Criteria) this;
        }

        public Criteria andVar55LessThan(BigDecimal value) {
            addCriterion("VAR_55 <", value, "var55");
            return (Criteria) this;
        }

        public Criteria andVar55LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_55 <=", value, "var55");
            return (Criteria) this;
        }

        public Criteria andVar55In(List<BigDecimal> values) {
            addCriterion("VAR_55 in", values, "var55");
            return (Criteria) this;
        }

        public Criteria andVar55NotIn(List<BigDecimal> values) {
            addCriterion("VAR_55 not in", values, "var55");
            return (Criteria) this;
        }

        public Criteria andVar55Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_55 between", value1, value2, "var55");
            return (Criteria) this;
        }

        public Criteria andVar55NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_55 not between", value1, value2, "var55");
            return (Criteria) this;
        }

        public Criteria andVar60IsNull() {
            addCriterion("VAR_60 is null");
            return (Criteria) this;
        }

        public Criteria andVar60IsNotNull() {
            addCriterion("VAR_60 is not null");
            return (Criteria) this;
        }

        public Criteria andVar60EqualTo(BigDecimal value) {
            addCriterion("VAR_60 =", value, "var60");
            return (Criteria) this;
        }

        public Criteria andVar60NotEqualTo(BigDecimal value) {
            addCriterion("VAR_60 <>", value, "var60");
            return (Criteria) this;
        }

        public Criteria andVar60GreaterThan(BigDecimal value) {
            addCriterion("VAR_60 >", value, "var60");
            return (Criteria) this;
        }

        public Criteria andVar60GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_60 >=", value, "var60");
            return (Criteria) this;
        }

        public Criteria andVar60LessThan(BigDecimal value) {
            addCriterion("VAR_60 <", value, "var60");
            return (Criteria) this;
        }

        public Criteria andVar60LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_60 <=", value, "var60");
            return (Criteria) this;
        }

        public Criteria andVar60In(List<BigDecimal> values) {
            addCriterion("VAR_60 in", values, "var60");
            return (Criteria) this;
        }

        public Criteria andVar60NotIn(List<BigDecimal> values) {
            addCriterion("VAR_60 not in", values, "var60");
            return (Criteria) this;
        }

        public Criteria andVar60Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_60 between", value1, value2, "var60");
            return (Criteria) this;
        }

        public Criteria andVar60NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_60 not between", value1, value2, "var60");
            return (Criteria) this;
        }

        public Criteria andVar70IsNull() {
            addCriterion("VAR_70 is null");
            return (Criteria) this;
        }

        public Criteria andVar70IsNotNull() {
            addCriterion("VAR_70 is not null");
            return (Criteria) this;
        }

        public Criteria andVar70EqualTo(BigDecimal value) {
            addCriterion("VAR_70 =", value, "var70");
            return (Criteria) this;
        }

        public Criteria andVar70NotEqualTo(BigDecimal value) {
            addCriterion("VAR_70 <>", value, "var70");
            return (Criteria) this;
        }

        public Criteria andVar70GreaterThan(BigDecimal value) {
            addCriterion("VAR_70 >", value, "var70");
            return (Criteria) this;
        }

        public Criteria andVar70GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_70 >=", value, "var70");
            return (Criteria) this;
        }

        public Criteria andVar70LessThan(BigDecimal value) {
            addCriterion("VAR_70 <", value, "var70");
            return (Criteria) this;
        }

        public Criteria andVar70LessThanOrEqualTo(BigDecimal value) {
            addCriterion("VAR_70 <=", value, "var70");
            return (Criteria) this;
        }

        public Criteria andVar70In(List<BigDecimal> values) {
            addCriterion("VAR_70 in", values, "var70");
            return (Criteria) this;
        }

        public Criteria andVar70NotIn(List<BigDecimal> values) {
            addCriterion("VAR_70 not in", values, "var70");
            return (Criteria) this;
        }

        public Criteria andVar70Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_70 between", value1, value2, "var70");
            return (Criteria) this;
        }

        public Criteria andVar70NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VAR_70 not between", value1, value2, "var70");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GP_DATA
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}