package com.ly.gp.mybatis.model.info;

public class GpDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.MARKET_DATE
     *
     * @mbggenerated
     */
    private String marketDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.CODE
     *
     * @return the value of GP_DATA.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.CODE
     *
     * @param code the value for GP_DATA.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.MARKET_DATE
     *
     * @return the value of GP_DATA.MARKET_DATE
     *
     * @mbggenerated
     */
    public String getMarketDate() {
        return marketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.MARKET_DATE
     *
     * @param marketDate the value for GP_DATA.MARKET_DATE
     *
     * @mbggenerated
     */
    public void setMarketDate(String marketDate) {
        this.marketDate = marketDate == null ? null : marketDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", marketDate=").append(marketDate);
        sb.append("]");
        return sb.toString();
    }
}