package com.ly.gp.mybatis.model.info;

import java.math.BigDecimal;
import java.util.Date;

public class GpData extends GpDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.OPEN_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal openPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.LOW_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal lowPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.HIGHT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal hightPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.FINAL_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal finalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.TRAD_COUNT
     *
     * @mbggenerated
     */
    private BigDecimal tradCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.TRAD_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal tradPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.COLLECT_NUM
     *
     * @mbggenerated
     */
    private Long collectNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.INCREASE
     *
     * @mbggenerated
     */
    private BigDecimal increase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.INCREASE_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal increaseMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_3
     *
     * @mbggenerated
     */
    private BigDecimal var3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_5
     *
     * @mbggenerated
     */
    private BigDecimal var5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_8
     *
     * @mbggenerated
     */
    private BigDecimal var8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_10
     *
     * @mbggenerated
     */
    private BigDecimal var10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_12
     *
     * @mbggenerated
     */
    private BigDecimal var12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_15
     *
     * @mbggenerated
     */
    private BigDecimal var15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_18
     *
     * @mbggenerated
     */
    private BigDecimal var18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_20
     *
     * @mbggenerated
     */
    private BigDecimal var20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_25
     *
     * @mbggenerated
     */
    private BigDecimal var25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_30
     *
     * @mbggenerated
     */
    private BigDecimal var30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_35
     *
     * @mbggenerated
     */
    private BigDecimal var35;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_40
     *
     * @mbggenerated
     */
    private BigDecimal var40;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_45
     *
     * @mbggenerated
     */
    private BigDecimal var45;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_50
     *
     * @mbggenerated
     */
    private BigDecimal var50;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_55
     *
     * @mbggenerated
     */
    private BigDecimal var55;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_60
     *
     * @mbggenerated
     */
    private BigDecimal var60;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_DATA.VAR_70
     *
     * @mbggenerated
     */
    private BigDecimal var70;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.OPEN_PRICE
     *
     * @return the value of GP_DATA.OPEN_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.OPEN_PRICE
     *
     * @param openPrice the value for GP_DATA.OPEN_PRICE
     *
     * @mbggenerated
     */
    public void setOpenPrice(BigDecimal openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.LOW_PRICE
     *
     * @return the value of GP_DATA.LOW_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getLowPrice() {
        return lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.LOW_PRICE
     *
     * @param lowPrice the value for GP_DATA.LOW_PRICE
     *
     * @mbggenerated
     */
    public void setLowPrice(BigDecimal lowPrice) {
        this.lowPrice = lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.HIGHT_PRICE
     *
     * @return the value of GP_DATA.HIGHT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getHightPrice() {
        return hightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.HIGHT_PRICE
     *
     * @param hightPrice the value for GP_DATA.HIGHT_PRICE
     *
     * @mbggenerated
     */
    public void setHightPrice(BigDecimal hightPrice) {
        this.hightPrice = hightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.FINAL_PRICE
     *
     * @return the value of GP_DATA.FINAL_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getFinalPrice() {
        return finalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.FINAL_PRICE
     *
     * @param finalPrice the value for GP_DATA.FINAL_PRICE
     *
     * @mbggenerated
     */
    public void setFinalPrice(BigDecimal finalPrice) {
        this.finalPrice = finalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.TRAD_COUNT
     *
     * @return the value of GP_DATA.TRAD_COUNT
     *
     * @mbggenerated
     */
    public BigDecimal getTradCount() {
        return tradCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.TRAD_COUNT
     *
     * @param tradCount the value for GP_DATA.TRAD_COUNT
     *
     * @mbggenerated
     */
    public void setTradCount(BigDecimal tradCount) {
        this.tradCount = tradCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.TRAD_PRICE
     *
     * @return the value of GP_DATA.TRAD_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getTradPrice() {
        return tradPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.TRAD_PRICE
     *
     * @param tradPrice the value for GP_DATA.TRAD_PRICE
     *
     * @mbggenerated
     */
    public void setTradPrice(BigDecimal tradPrice) {
        this.tradPrice = tradPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.CREATE_DATE
     *
     * @return the value of GP_DATA.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.CREATE_DATE
     *
     * @param createDate the value for GP_DATA.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.COLLECT_NUM
     *
     * @return the value of GP_DATA.COLLECT_NUM
     *
     * @mbggenerated
     */
    public Long getCollectNum() {
        return collectNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.COLLECT_NUM
     *
     * @param collectNum the value for GP_DATA.COLLECT_NUM
     *
     * @mbggenerated
     */
    public void setCollectNum(Long collectNum) {
        this.collectNum = collectNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.INCREASE
     *
     * @return the value of GP_DATA.INCREASE
     *
     * @mbggenerated
     */
    public BigDecimal getIncrease() {
        return increase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.INCREASE
     *
     * @param increase the value for GP_DATA.INCREASE
     *
     * @mbggenerated
     */
    public void setIncrease(BigDecimal increase) {
        this.increase = increase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.INCREASE_MONEY
     *
     * @return the value of GP_DATA.INCREASE_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getIncreaseMoney() {
        return increaseMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.INCREASE_MONEY
     *
     * @param increaseMoney the value for GP_DATA.INCREASE_MONEY
     *
     * @mbggenerated
     */
    public void setIncreaseMoney(BigDecimal increaseMoney) {
        this.increaseMoney = increaseMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_3
     *
     * @return the value of GP_DATA.VAR_3
     *
     * @mbggenerated
     */
    public BigDecimal getVar3() {
        return var3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_3
     *
     * @param var3 the value for GP_DATA.VAR_3
     *
     * @mbggenerated
     */
    public void setVar3(BigDecimal var3) {
        this.var3 = var3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_5
     *
     * @return the value of GP_DATA.VAR_5
     *
     * @mbggenerated
     */
    public BigDecimal getVar5() {
        return var5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_5
     *
     * @param var5 the value for GP_DATA.VAR_5
     *
     * @mbggenerated
     */
    public void setVar5(BigDecimal var5) {
        this.var5 = var5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_8
     *
     * @return the value of GP_DATA.VAR_8
     *
     * @mbggenerated
     */
    public BigDecimal getVar8() {
        return var8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_8
     *
     * @param var8 the value for GP_DATA.VAR_8
     *
     * @mbggenerated
     */
    public void setVar8(BigDecimal var8) {
        this.var8 = var8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_10
     *
     * @return the value of GP_DATA.VAR_10
     *
     * @mbggenerated
     */
    public BigDecimal getVar10() {
        return var10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_10
     *
     * @param var10 the value for GP_DATA.VAR_10
     *
     * @mbggenerated
     */
    public void setVar10(BigDecimal var10) {
        this.var10 = var10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_12
     *
     * @return the value of GP_DATA.VAR_12
     *
     * @mbggenerated
     */
    public BigDecimal getVar12() {
        return var12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_12
     *
     * @param var12 the value for GP_DATA.VAR_12
     *
     * @mbggenerated
     */
    public void setVar12(BigDecimal var12) {
        this.var12 = var12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_15
     *
     * @return the value of GP_DATA.VAR_15
     *
     * @mbggenerated
     */
    public BigDecimal getVar15() {
        return var15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_15
     *
     * @param var15 the value for GP_DATA.VAR_15
     *
     * @mbggenerated
     */
    public void setVar15(BigDecimal var15) {
        this.var15 = var15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_18
     *
     * @return the value of GP_DATA.VAR_18
     *
     * @mbggenerated
     */
    public BigDecimal getVar18() {
        return var18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_18
     *
     * @param var18 the value for GP_DATA.VAR_18
     *
     * @mbggenerated
     */
    public void setVar18(BigDecimal var18) {
        this.var18 = var18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_20
     *
     * @return the value of GP_DATA.VAR_20
     *
     * @mbggenerated
     */
    public BigDecimal getVar20() {
        return var20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_20
     *
     * @param var20 the value for GP_DATA.VAR_20
     *
     * @mbggenerated
     */
    public void setVar20(BigDecimal var20) {
        this.var20 = var20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_25
     *
     * @return the value of GP_DATA.VAR_25
     *
     * @mbggenerated
     */
    public BigDecimal getVar25() {
        return var25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_25
     *
     * @param var25 the value for GP_DATA.VAR_25
     *
     * @mbggenerated
     */
    public void setVar25(BigDecimal var25) {
        this.var25 = var25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_30
     *
     * @return the value of GP_DATA.VAR_30
     *
     * @mbggenerated
     */
    public BigDecimal getVar30() {
        return var30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_30
     *
     * @param var30 the value for GP_DATA.VAR_30
     *
     * @mbggenerated
     */
    public void setVar30(BigDecimal var30) {
        this.var30 = var30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_35
     *
     * @return the value of GP_DATA.VAR_35
     *
     * @mbggenerated
     */
    public BigDecimal getVar35() {
        return var35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_35
     *
     * @param var35 the value for GP_DATA.VAR_35
     *
     * @mbggenerated
     */
    public void setVar35(BigDecimal var35) {
        this.var35 = var35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_40
     *
     * @return the value of GP_DATA.VAR_40
     *
     * @mbggenerated
     */
    public BigDecimal getVar40() {
        return var40;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_40
     *
     * @param var40 the value for GP_DATA.VAR_40
     *
     * @mbggenerated
     */
    public void setVar40(BigDecimal var40) {
        this.var40 = var40;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_45
     *
     * @return the value of GP_DATA.VAR_45
     *
     * @mbggenerated
     */
    public BigDecimal getVar45() {
        return var45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_45
     *
     * @param var45 the value for GP_DATA.VAR_45
     *
     * @mbggenerated
     */
    public void setVar45(BigDecimal var45) {
        this.var45 = var45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_50
     *
     * @return the value of GP_DATA.VAR_50
     *
     * @mbggenerated
     */
    public BigDecimal getVar50() {
        return var50;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_50
     *
     * @param var50 the value for GP_DATA.VAR_50
     *
     * @mbggenerated
     */
    public void setVar50(BigDecimal var50) {
        this.var50 = var50;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_55
     *
     * @return the value of GP_DATA.VAR_55
     *
     * @mbggenerated
     */
    public BigDecimal getVar55() {
        return var55;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_55
     *
     * @param var55 the value for GP_DATA.VAR_55
     *
     * @mbggenerated
     */
    public void setVar55(BigDecimal var55) {
        this.var55 = var55;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_60
     *
     * @return the value of GP_DATA.VAR_60
     *
     * @mbggenerated
     */
    public BigDecimal getVar60() {
        return var60;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_60
     *
     * @param var60 the value for GP_DATA.VAR_60
     *
     * @mbggenerated
     */
    public void setVar60(BigDecimal var60) {
        this.var60 = var60;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_DATA.VAR_70
     *
     * @return the value of GP_DATA.VAR_70
     *
     * @mbggenerated
     */
    public BigDecimal getVar70() {
        return var70;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_DATA.VAR_70
     *
     * @param var70 the value for GP_DATA.VAR_70
     *
     * @mbggenerated
     */
    public void setVar70(BigDecimal var70) {
        this.var70 = var70;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", openPrice=").append(openPrice);
        sb.append(", lowPrice=").append(lowPrice);
        sb.append(", hightPrice=").append(hightPrice);
        sb.append(", finalPrice=").append(finalPrice);
        sb.append(", tradCount=").append(tradCount);
        sb.append(", tradPrice=").append(tradPrice);
        sb.append(", createDate=").append(createDate);
        sb.append(", collectNum=").append(collectNum);
        sb.append(", increase=").append(increase);
        sb.append(", increaseMoney=").append(increaseMoney);
        sb.append(", var3=").append(var3);
        sb.append(", var5=").append(var5);
        sb.append(", var8=").append(var8);
        sb.append(", var10=").append(var10);
        sb.append(", var12=").append(var12);
        sb.append(", var15=").append(var15);
        sb.append(", var18=").append(var18);
        sb.append(", var20=").append(var20);
        sb.append(", var25=").append(var25);
        sb.append(", var30=").append(var30);
        sb.append(", var35=").append(var35);
        sb.append(", var40=").append(var40);
        sb.append(", var45=").append(var45);
        sb.append(", var50=").append(var50);
        sb.append(", var55=").append(var55);
        sb.append(", var60=").append(var60);
        sb.append(", var70=").append(var70);
        sb.append("]");
        return sb.toString();
    }
}