package com.ly.gp.mybatis.model.info;

import java.math.BigDecimal;
import java.util.Date;

public class GpInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_INFO.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_INFO.SHORT_NAME
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_INFO.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_INFO.STYPE
     *
     * @mbggenerated
     */
    private String stype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_INFO.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_INFO.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_INFO.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_INFO.COLL_DATES
     *
     * @mbggenerated
     */
    private String collDates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GP_INFO.CIR_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal cirValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_INFO.CODE
     *
     * @return the value of GP_INFO.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_INFO.CODE
     *
     * @param code the value for GP_INFO.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_INFO.SHORT_NAME
     *
     * @return the value of GP_INFO.SHORT_NAME
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_INFO.SHORT_NAME
     *
     * @param shortName the value for GP_INFO.SHORT_NAME
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_INFO.NAME
     *
     * @return the value of GP_INFO.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_INFO.NAME
     *
     * @param name the value for GP_INFO.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_INFO.STYPE
     *
     * @return the value of GP_INFO.STYPE
     *
     * @mbggenerated
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_INFO.STYPE
     *
     * @param stype the value for GP_INFO.STYPE
     *
     * @mbggenerated
     */
    public void setStype(String stype) {
        this.stype = stype == null ? null : stype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_INFO.STATE
     *
     * @return the value of GP_INFO.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_INFO.STATE
     *
     * @param state the value for GP_INFO.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_INFO.REMARK
     *
     * @return the value of GP_INFO.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_INFO.REMARK
     *
     * @param remark the value for GP_INFO.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_INFO.CREATE_DATE
     *
     * @return the value of GP_INFO.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_INFO.CREATE_DATE
     *
     * @param createDate the value for GP_INFO.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_INFO.COLL_DATES
     *
     * @return the value of GP_INFO.COLL_DATES
     *
     * @mbggenerated
     */
    public String getCollDates() {
        return collDates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_INFO.COLL_DATES
     *
     * @param collDates the value for GP_INFO.COLL_DATES
     *
     * @mbggenerated
     */
    public void setCollDates(String collDates) {
        this.collDates = collDates == null ? null : collDates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GP_INFO.CIR_VALUE
     *
     * @return the value of GP_INFO.CIR_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getCirValue() {
        return cirValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GP_INFO.CIR_VALUE
     *
     * @param cirValue the value for GP_INFO.CIR_VALUE
     *
     * @mbggenerated
     */
    public void setCirValue(BigDecimal cirValue) {
        this.cirValue = cirValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", shortName=").append(shortName);
        sb.append(", name=").append(name);
        sb.append(", stype=").append(stype);
        sb.append(", state=").append(state);
        sb.append(", remark=").append(remark);
        sb.append(", createDate=").append(createDate);
        sb.append(", collDates=").append(collDates);
        sb.append(", cirValue=").append(cirValue);
        sb.append("]");
        return sb.toString();
    }
}