package com.ly.back.framework.mybatis.model.sys;

import java.math.BigDecimal;
import java.util.Date;

public class SysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.MENU_ID
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.MENU_NAME
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.MENU_TYPE
     *
     * @mbggenerated
     */
    private String menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.MENU_LEVEL
     *
     * @mbggenerated
     */
    private String menuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.PARENT_MENU_ID
     *
     * @mbggenerated
     */
    private String parentMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.SORT_NUM
     *
     * @mbggenerated
     */
    private BigDecimal sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.MENU_URL
     *
     * @mbggenerated
     */
    private String menuUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.MENU_ID
     *
     * @return the value of SYS_MENU.MENU_ID
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.MENU_ID
     *
     * @param menuId the value for SYS_MENU.MENU_ID
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.MENU_NAME
     *
     * @return the value of SYS_MENU.MENU_NAME
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.MENU_NAME
     *
     * @param menuName the value for SYS_MENU.MENU_NAME
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.MENU_TYPE
     *
     * @return the value of SYS_MENU.MENU_TYPE
     *
     * @mbggenerated
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.MENU_TYPE
     *
     * @param menuType the value for SYS_MENU.MENU_TYPE
     *
     * @mbggenerated
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.MENU_LEVEL
     *
     * @return the value of SYS_MENU.MENU_LEVEL
     *
     * @mbggenerated
     */
    public String getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.MENU_LEVEL
     *
     * @param menuLevel the value for SYS_MENU.MENU_LEVEL
     *
     * @mbggenerated
     */
    public void setMenuLevel(String menuLevel) {
        this.menuLevel = menuLevel == null ? null : menuLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.PARENT_MENU_ID
     *
     * @return the value of SYS_MENU.PARENT_MENU_ID
     *
     * @mbggenerated
     */
    public String getParentMenuId() {
        return parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.PARENT_MENU_ID
     *
     * @param parentMenuId the value for SYS_MENU.PARENT_MENU_ID
     *
     * @mbggenerated
     */
    public void setParentMenuId(String parentMenuId) {
        this.parentMenuId = parentMenuId == null ? null : parentMenuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.SORT_NUM
     *
     * @return the value of SYS_MENU.SORT_NUM
     *
     * @mbggenerated
     */
    public BigDecimal getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.SORT_NUM
     *
     * @param sortNum the value for SYS_MENU.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(BigDecimal sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.CREATE_DATE
     *
     * @return the value of SYS_MENU.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.CREATE_DATE
     *
     * @param createDate the value for SYS_MENU.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.CREATE_USER
     *
     * @return the value of SYS_MENU.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.CREATE_USER
     *
     * @param createUser the value for SYS_MENU.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.STATE
     *
     * @return the value of SYS_MENU.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.STATE
     *
     * @param state the value for SYS_MENU.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_MENU.MENU_URL
     *
     * @return the value of SYS_MENU.MENU_URL
     *
     * @mbggenerated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_MENU.MENU_URL
     *
     * @param menuUrl the value for SYS_MENU.MENU_URL
     *
     * @mbggenerated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuType=").append(menuType);
        sb.append(", menuLevel=").append(menuLevel);
        sb.append(", parentMenuId=").append(parentMenuId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", state=").append(state);
        sb.append(", menuUrl=").append(menuUrl);
        sb.append("]");
        return sb.toString();
    }
}