package com.ly.back.framework.mybatis.model.sys;

public class SysQueryJs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_JS.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_JS.JS_PATH
     *
     * @mbggenerated
     */
    private String jsPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_JS.QUERY_ID
     *
     * @mbggenerated
     */
    private String queryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_JS.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_JS.ID
     *
     * @return the value of SYS_QUERY_JS.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_JS.ID
     *
     * @param id the value for SYS_QUERY_JS.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_JS.JS_PATH
     *
     * @return the value of SYS_QUERY_JS.JS_PATH
     *
     * @mbggenerated
     */
    public String getJsPath() {
        return jsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_JS.JS_PATH
     *
     * @param jsPath the value for SYS_QUERY_JS.JS_PATH
     *
     * @mbggenerated
     */
    public void setJsPath(String jsPath) {
        this.jsPath = jsPath == null ? null : jsPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_JS.QUERY_ID
     *
     * @return the value of SYS_QUERY_JS.QUERY_ID
     *
     * @mbggenerated
     */
    public String getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_JS.QUERY_ID
     *
     * @param queryId the value for SYS_QUERY_JS.QUERY_ID
     *
     * @mbggenerated
     */
    public void setQueryId(String queryId) {
        this.queryId = queryId == null ? null : queryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_JS.REMARK
     *
     * @return the value of SYS_QUERY_JS.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_JS.REMARK
     *
     * @param remark the value for SYS_QUERY_JS.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_JS
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", jsPath=").append(jsPath);
        sb.append(", queryId=").append(queryId);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}