package com.ly.back.framework.mybatis.model.sys;

import java.math.BigDecimal;

public class SysQueryField {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FIELD.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FIELD.FIELD
     *
     * @mbggenerated
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FIELD.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FIELD.WIDTH
     *
     * @mbggenerated
     */
    private String width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FIELD.FILED_SORT
     *
     * @mbggenerated
     */
    private BigDecimal filedSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FIELD.QUERY_ID
     *
     * @mbggenerated
     */
    private String queryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FIELD.HIDDEN
     *
     * @mbggenerated
     */
    private String hidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FIELD.IS_KEY
     *
     * @mbggenerated
     */
    private String isKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FIELD.SUB_LENGTH
     *
     * @mbggenerated
     */
    private Short subLength;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FIELD.ID
     *
     * @return the value of SYS_QUERY_FIELD.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FIELD.ID
     *
     * @param id the value for SYS_QUERY_FIELD.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FIELD.FIELD
     *
     * @return the value of SYS_QUERY_FIELD.FIELD
     *
     * @mbggenerated
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FIELD.FIELD
     *
     * @param field the value for SYS_QUERY_FIELD.FIELD
     *
     * @mbggenerated
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FIELD.TITLE
     *
     * @return the value of SYS_QUERY_FIELD.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FIELD.TITLE
     *
     * @param title the value for SYS_QUERY_FIELD.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FIELD.WIDTH
     *
     * @return the value of SYS_QUERY_FIELD.WIDTH
     *
     * @mbggenerated
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FIELD.WIDTH
     *
     * @param width the value for SYS_QUERY_FIELD.WIDTH
     *
     * @mbggenerated
     */
    public void setWidth(String width) {
        this.width = width == null ? null : width.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FIELD.FILED_SORT
     *
     * @return the value of SYS_QUERY_FIELD.FILED_SORT
     *
     * @mbggenerated
     */
    public BigDecimal getFiledSort() {
        return filedSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FIELD.FILED_SORT
     *
     * @param filedSort the value for SYS_QUERY_FIELD.FILED_SORT
     *
     * @mbggenerated
     */
    public void setFiledSort(BigDecimal filedSort) {
        this.filedSort = filedSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FIELD.QUERY_ID
     *
     * @return the value of SYS_QUERY_FIELD.QUERY_ID
     *
     * @mbggenerated
     */
    public String getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FIELD.QUERY_ID
     *
     * @param queryId the value for SYS_QUERY_FIELD.QUERY_ID
     *
     * @mbggenerated
     */
    public void setQueryId(String queryId) {
        this.queryId = queryId == null ? null : queryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FIELD.HIDDEN
     *
     * @return the value of SYS_QUERY_FIELD.HIDDEN
     *
     * @mbggenerated
     */
    public String getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FIELD.HIDDEN
     *
     * @param hidden the value for SYS_QUERY_FIELD.HIDDEN
     *
     * @mbggenerated
     */
    public void setHidden(String hidden) {
        this.hidden = hidden == null ? null : hidden.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FIELD.IS_KEY
     *
     * @return the value of SYS_QUERY_FIELD.IS_KEY
     *
     * @mbggenerated
     */
    public String getIsKey() {
        return isKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FIELD.IS_KEY
     *
     * @param isKey the value for SYS_QUERY_FIELD.IS_KEY
     *
     * @mbggenerated
     */
    public void setIsKey(String isKey) {
        this.isKey = isKey == null ? null : isKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FIELD.SUB_LENGTH
     *
     * @return the value of SYS_QUERY_FIELD.SUB_LENGTH
     *
     * @mbggenerated
     */
    public Short getSubLength() {
        return subLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FIELD.SUB_LENGTH
     *
     * @param subLength the value for SYS_QUERY_FIELD.SUB_LENGTH
     *
     * @mbggenerated
     */
    public void setSubLength(Short subLength) {
        this.subLength = subLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FIELD
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", field=").append(field);
        sb.append(", title=").append(title);
        sb.append(", width=").append(width);
        sb.append(", filedSort=").append(filedSort);
        sb.append(", queryId=").append(queryId);
        sb.append(", hidden=").append(hidden);
        sb.append(", isKey=").append(isKey);
        sb.append(", subLength=").append(subLength);
        sb.append("]");
        return sb.toString();
    }
}