package com.ly.back.framework.mybatis.model.sys;

import java.math.BigDecimal;
import java.util.Date;

public class SysQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.PAGE_SIZE
     *
     * @mbggenerated
     */
    private BigDecimal pageSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.SINGLE_SELECT
     *
     * @mbggenerated
     */
    private String singleSelect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.IS_TOOLBAR
     *
     * @mbggenerated
     */
    private String isToolbar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.PARAM_COLSPAN
     *
     * @mbggenerated
     */
    private BigDecimal paramColspan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY.SQL
     *
     * @mbggenerated
     */
    private String sql;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.ID
     *
     * @return the value of SYS_QUERY.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.ID
     *
     * @param id the value for SYS_QUERY.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.NAME
     *
     * @return the value of SYS_QUERY.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.NAME
     *
     * @param name the value for SYS_QUERY.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.REMARK
     *
     * @return the value of SYS_QUERY.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.REMARK
     *
     * @param remark the value for SYS_QUERY.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.STATE
     *
     * @return the value of SYS_QUERY.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.STATE
     *
     * @param state the value for SYS_QUERY.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.CREATE_TIME
     *
     * @return the value of SYS_QUERY.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.CREATE_TIME
     *
     * @param createTime the value for SYS_QUERY.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.CREATE_USER
     *
     * @return the value of SYS_QUERY.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.CREATE_USER
     *
     * @param createUser the value for SYS_QUERY.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.PAGE_SIZE
     *
     * @return the value of SYS_QUERY.PAGE_SIZE
     *
     * @mbggenerated
     */
    public BigDecimal getPageSize() {
        return pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.PAGE_SIZE
     *
     * @param pageSize the value for SYS_QUERY.PAGE_SIZE
     *
     * @mbggenerated
     */
    public void setPageSize(BigDecimal pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.SINGLE_SELECT
     *
     * @return the value of SYS_QUERY.SINGLE_SELECT
     *
     * @mbggenerated
     */
    public String getSingleSelect() {
        return singleSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.SINGLE_SELECT
     *
     * @param singleSelect the value for SYS_QUERY.SINGLE_SELECT
     *
     * @mbggenerated
     */
    public void setSingleSelect(String singleSelect) {
        this.singleSelect = singleSelect == null ? null : singleSelect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.IS_TOOLBAR
     *
     * @return the value of SYS_QUERY.IS_TOOLBAR
     *
     * @mbggenerated
     */
    public String getIsToolbar() {
        return isToolbar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.IS_TOOLBAR
     *
     * @param isToolbar the value for SYS_QUERY.IS_TOOLBAR
     *
     * @mbggenerated
     */
    public void setIsToolbar(String isToolbar) {
        this.isToolbar = isToolbar == null ? null : isToolbar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.PARAM_COLSPAN
     *
     * @return the value of SYS_QUERY.PARAM_COLSPAN
     *
     * @mbggenerated
     */
    public BigDecimal getParamColspan() {
        return paramColspan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.PARAM_COLSPAN
     *
     * @param paramColspan the value for SYS_QUERY.PARAM_COLSPAN
     *
     * @mbggenerated
     */
    public void setParamColspan(BigDecimal paramColspan) {
        this.paramColspan = paramColspan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY.SQL
     *
     * @return the value of SYS_QUERY.SQL
     *
     * @mbggenerated
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY.SQL
     *
     * @param sql the value for SYS_QUERY.SQL
     *
     * @mbggenerated
     */
    public void setSql(String sql) {
        this.sql = sql == null ? null : sql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", remark=").append(remark);
        sb.append(", state=").append(state);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", pageSize=").append(pageSize);
        sb.append(", singleSelect=").append(singleSelect);
        sb.append(", isToolbar=").append(isToolbar);
        sb.append(", paramColspan=").append(paramColspan);
        sb.append(", sql=").append(sql);
        sb.append("]");
        return sb.toString();
    }
}