package com.ly.back.framework.mybatis.model.sys;

public class SysQueryFormType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FORM_TYPE.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FORM_TYPE.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_FORM_TYPE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FORM_TYPE.ID
     *
     * @return the value of SYS_QUERY_FORM_TYPE.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FORM_TYPE.ID
     *
     * @param id the value for SYS_QUERY_FORM_TYPE.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FORM_TYPE.NAME
     *
     * @return the value of SYS_QUERY_FORM_TYPE.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FORM_TYPE.NAME
     *
     * @param name the value for SYS_QUERY_FORM_TYPE.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_FORM_TYPE.REMARK
     *
     * @return the value of SYS_QUERY_FORM_TYPE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_FORM_TYPE.REMARK
     *
     * @param remark the value for SYS_QUERY_FORM_TYPE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_FORM_TYPE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}