package com.ly.back.framework.mybatis.model.sys;

import java.math.BigDecimal;

public class SysQueryParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.QUERY_ID
     *
     * @mbggenerated
     */
    private String queryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.PARAM_NAME
     *
     * @mbggenerated
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.QUERY_TYPE
     *
     * @mbggenerated
     */
    private String queryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.PARAM_DEF
     *
     * @mbggenerated
     */
    private String paramDef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.PARAM_FIELD
     *
     * @mbggenerated
     */
    private String paramField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.PARAM_SORT
     *
     * @mbggenerated
     */
    private BigDecimal paramSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.PARAM_INPUT_SQL
     *
     * @mbggenerated
     */
    private String paramInputSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.FROM_TYPE
     *
     * @mbggenerated
     */
    private String fromType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.REQUIRED
     *
     * @mbggenerated
     */
    private String required;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_QUERY_PARAM.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.ID
     *
     * @return the value of SYS_QUERY_PARAM.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.ID
     *
     * @param id the value for SYS_QUERY_PARAM.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.QUERY_ID
     *
     * @return the value of SYS_QUERY_PARAM.QUERY_ID
     *
     * @mbggenerated
     */
    public String getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.QUERY_ID
     *
     * @param queryId the value for SYS_QUERY_PARAM.QUERY_ID
     *
     * @mbggenerated
     */
    public void setQueryId(String queryId) {
        this.queryId = queryId == null ? null : queryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.PARAM_NAME
     *
     * @return the value of SYS_QUERY_PARAM.PARAM_NAME
     *
     * @mbggenerated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.PARAM_NAME
     *
     * @param paramName the value for SYS_QUERY_PARAM.PARAM_NAME
     *
     * @mbggenerated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.QUERY_TYPE
     *
     * @return the value of SYS_QUERY_PARAM.QUERY_TYPE
     *
     * @mbggenerated
     */
    public String getQueryType() {
        return queryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.QUERY_TYPE
     *
     * @param queryType the value for SYS_QUERY_PARAM.QUERY_TYPE
     *
     * @mbggenerated
     */
    public void setQueryType(String queryType) {
        this.queryType = queryType == null ? null : queryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.PARAM_DEF
     *
     * @return the value of SYS_QUERY_PARAM.PARAM_DEF
     *
     * @mbggenerated
     */
    public String getParamDef() {
        return paramDef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.PARAM_DEF
     *
     * @param paramDef the value for SYS_QUERY_PARAM.PARAM_DEF
     *
     * @mbggenerated
     */
    public void setParamDef(String paramDef) {
        this.paramDef = paramDef == null ? null : paramDef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.PARAM_FIELD
     *
     * @return the value of SYS_QUERY_PARAM.PARAM_FIELD
     *
     * @mbggenerated
     */
    public String getParamField() {
        return paramField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.PARAM_FIELD
     *
     * @param paramField the value for SYS_QUERY_PARAM.PARAM_FIELD
     *
     * @mbggenerated
     */
    public void setParamField(String paramField) {
        this.paramField = paramField == null ? null : paramField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.PARAM_SORT
     *
     * @return the value of SYS_QUERY_PARAM.PARAM_SORT
     *
     * @mbggenerated
     */
    public BigDecimal getParamSort() {
        return paramSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.PARAM_SORT
     *
     * @param paramSort the value for SYS_QUERY_PARAM.PARAM_SORT
     *
     * @mbggenerated
     */
    public void setParamSort(BigDecimal paramSort) {
        this.paramSort = paramSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.PARAM_INPUT_SQL
     *
     * @return the value of SYS_QUERY_PARAM.PARAM_INPUT_SQL
     *
     * @mbggenerated
     */
    public String getParamInputSql() {
        return paramInputSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.PARAM_INPUT_SQL
     *
     * @param paramInputSql the value for SYS_QUERY_PARAM.PARAM_INPUT_SQL
     *
     * @mbggenerated
     */
    public void setParamInputSql(String paramInputSql) {
        this.paramInputSql = paramInputSql == null ? null : paramInputSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.FROM_TYPE
     *
     * @return the value of SYS_QUERY_PARAM.FROM_TYPE
     *
     * @mbggenerated
     */
    public String getFromType() {
        return fromType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.FROM_TYPE
     *
     * @param fromType the value for SYS_QUERY_PARAM.FROM_TYPE
     *
     * @mbggenerated
     */
    public void setFromType(String fromType) {
        this.fromType = fromType == null ? null : fromType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.REQUIRED
     *
     * @return the value of SYS_QUERY_PARAM.REQUIRED
     *
     * @mbggenerated
     */
    public String getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.REQUIRED
     *
     * @param required the value for SYS_QUERY_PARAM.REQUIRED
     *
     * @mbggenerated
     */
    public void setRequired(String required) {
        this.required = required == null ? null : required.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_QUERY_PARAM.REMARK
     *
     * @return the value of SYS_QUERY_PARAM.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_QUERY_PARAM.REMARK
     *
     * @param remark the value for SYS_QUERY_PARAM.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_QUERY_PARAM
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", queryId=").append(queryId);
        sb.append(", paramName=").append(paramName);
        sb.append(", queryType=").append(queryType);
        sb.append(", paramDef=").append(paramDef);
        sb.append(", paramField=").append(paramField);
        sb.append(", paramSort=").append(paramSort);
        sb.append(", paramInputSql=").append(paramInputSql);
        sb.append(", fromType=").append(fromType);
        sb.append(", required=").append(required);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}