package com.ly.gp.mybatis.mapper.info;

import com.ly.gp.mybatis.model.info.GpData;
import com.ly.gp.mybatis.model.info.GpDataExample;
import com.ly.gp.mybatis.model.info.GpDataKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GpDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    int countByExample(GpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    int deleteByExample(GpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(GpDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    int insert(GpData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    int insertSelective(GpData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    List<GpData> selectByExampleWithRowbounds(GpDataExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    List<GpData> selectByExample(GpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    GpData selectByPrimaryKey(GpDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GpData record, @Param("example") GpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GpData record, @Param("example") GpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GpData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_DATA
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GpData record);
}