package com.ly.gp.mybatis.mapper.info;

import com.ly.gp.mybatis.model.info.GpInfo;
import com.ly.gp.mybatis.model.info.GpInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GpInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    int countByExample(GpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(GpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    int insert(GpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    int insertSelective(GpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    List<GpInfo> selectByExampleWithRowbounds(GpInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    List<GpInfo> selectByExample(GpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    GpInfo selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GpInfo record, @Param("example") GpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GpInfo record, @Param("example") GpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GP_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GpInfo record);
}